name: Test
on:
  push:
    branches:
      - test
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    name: Build

    strategy:
      matrix:
        runs-on: [windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v3

      - run: mkdir -p path/to/artifact

      - run: echo hello > path/to/artifact/world.txt

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact/world.txt
